//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace Empl.Properties {
=======
namespace Dacto.Properties {
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
<<<<<<< HEAD
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empl.Properties.Resources", typeof(Resources).Assembly);
=======
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dacto.Properties.Resources", typeof(Resources).Assembly);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
=======
        internal static System.Drawing.Bitmap _123033 {
            get {
                object obj = ResourceManager.GetObject("_123033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
        internal static System.Drawing.Bitmap _1485477104_basket_78591 {
            get {
                object obj = ResourceManager.GetObject("1485477104-basket_78591", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _1485477104_basket_785911 {
            get {
                object obj = ResourceManager.GetObject("1485477104-basket_785911", resourceCulture);
=======
        internal static System.Drawing.Bitmap _19_104865 {
            get {
                object obj = ResourceManager.GetObject("19_104865", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _4202011emailgmaillogomailsocialsocialmedia_115677_115624__1_ {
            get {
                object obj = ResourceManager.GetObject("4202011emailgmaillogomailsocialsocialmedia-115677_115624 (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap _4202011emailgmaillogomailsocialsocialmedia_115677_115624__2_ {
            get {
                object obj = ResourceManager.GetObject("4202011emailgmaillogomailsocialsocialmedia-115677_115624 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _588hospital_100778 {
            get {
                object obj = ResourceManager.GetObject("588hospital_100778", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_27013 {
            get {
                object obj = ResourceManager.GetObject("Add_27013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap avatar_face_man_boy_male_profile_smiley_happy_people_icon_181657 {
            get {
                object obj = ResourceManager.GetObject("avatar_face_man_boy_male_profile_smiley_happy_people_icon_181657", resourceCulture);
=======
        internal static System.Drawing.Bitmap alarm_clock_icon_icons_com_60726 {
            get {
                object obj = ResourceManager.GetObject("alarm-clock_icon-icons.com_60726", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_reload_15002 {
            get {
                object obj = ResourceManager.GetObject("button_reload_15002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_time_event_date_icon_220247 {
            get {
                object obj = ResourceManager.GetObject("calendar_time_event_date_icon_220247", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap call_phone_22173 {
            get {
                object obj = ResourceManager.GetObject("call_phone_22173", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap campus_school_building_front_icon_icons_com_75490 {
            get {
                object obj = ResourceManager.GetObject("campus_school_building_front_icon-icons.com_75490", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
=======
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
        internal static System.Drawing.Bitmap cancel_77947 {
            get {
                object obj = ResourceManager.GetObject("cancel_77947", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap clipboard_notes_list_tasks_icon_191193__1_ {
            get {
                object obj = ResourceManager.GetObject("clipboard_notes_list_tasks_icon_191193 (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap cancel_779471 {
            get {
                object obj = ResourceManager.GetObject("cancel_779471", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap Contacts_31110 {
            get {
                object obj = ResourceManager.GetObject("Contacts_31110", resourceCulture);
=======
        internal static System.Drawing.Bitmap diagnosis_coronavirus_covid_symstoms_information_checklist_icon_141627 {
            get {
                object obj = ResourceManager.GetObject("diagnosis_coronavirus_covid_symstoms_information_checklist_icon_141627", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e9def10cd16308da93daad122c7b8a8f {
            get {
                object obj = ResourceManager.GetObject("e9def10cd16308da93daad122c7b8a8f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e9def10cd16308da93daad122c7b8a8f1 {
            get {
                object obj = ResourceManager.GetObject("e9def10cd16308da93daad122c7b8a8f1", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_directory_reload_refresh_108581 {
            get {
                object obj = ResourceManager.GetObject("folder-directory-reload-refresh_108581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap location_map_pin_mark_icon_148685 {
            get {
                object obj = ResourceManager.GetObject("location_map_pin_mark_icon_148685", resourceCulture);
=======
        internal static System.Drawing.Bitmap iconfinder_3_avatar_2754579_120516 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-3-avatar-2754579_120516", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap number7_numero_12635 {
            get {
                object obj = ResourceManager.GetObject("number7_numero_12635", resourceCulture);
=======
        internal static System.Drawing.Bitmap iconfinder_dedicatedipaddress_4263513_117864 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-dedicatedipaddress-4263513_117864", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap Overtime_80_icon_icons_com_57296 {
            get {
                object obj = ResourceManager.GetObject("Overtime-80_icon-icons.com_57296", resourceCulture);
=======
        internal static System.Drawing.Bitmap medical_03_icon_icons_com_73941 {
            get {
                object obj = ResourceManager.GetObject("medical-03_icon-icons.com_73941", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap search_icon_229534 {
            get {
                object obj = ResourceManager.GetObject("search_icon_229534", resourceCulture);
=======
        internal static System.Drawing.Bitmap medical_29_icon_icons_com_73943 {
            get {
                object obj = ResourceManager.GetObject("medical-29_icon-icons.com_73943", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Microsoft_Excel_01_25074 {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Excel-01_25074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIF {
            get {
                object obj = ResourceManager.GetObject("OIF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIP__1_ {
            get {
                object obj = ResourceManager.GetObject("OIP (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIP__2_ {
            get {
                object obj = ResourceManager.GetObject("OIP (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_user_customer_female_people_1689 {
            get {
                object obj = ResourceManager.GetObject("person_user_customer_female_people_1689", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_magnifier_icon_145939 {
            get {
                object obj = ResourceManager.GetObject("search_magnifier_icon_145939", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap task_planning_scheduling_roadmap_project_plan_project_management_icon_262962 {
            get {
                object obj = ResourceManager.GetObject("task_planning_scheduling_roadmap_project_plan_project_management_icon_262962", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trade_report_reports_documents_2351__1_ {
            get {
                object obj = ResourceManager.GetObject("trade_report_reports_documents_2351 (1)", resourceCulture);
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usd_crypto_cryptocurrency_cryptocurrencies_cash_money_bank_payment_95707__1_ {
            get {
                object obj = ResourceManager.GetObject("usd-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95707 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
<<<<<<< HEAD
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_femalecustomer_person_usuari_9885 {
            get {
                object obj = ResourceManager.GetObject("user_femalecustomer_person_usuari_9885", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userrating_115845_115824 {
            get {
                object obj = ResourceManager.GetObject("userrating-115845_115824", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap تنزيل__1_ {
            get {
                object obj = ResourceManager.GetObject("تنزيل (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
=======
>>>>>>> 03ad57bdd424fdd7c91b73008c93f4d9b6541004
    }
}
